export const runtime = "nodejs";
export const dynamic = "force-dynamic";
import {NextRequest,NextResponse} from "next/server";
import {z} from "zod";
import {getCurrentSession} from "@/lib/auth";
import {CREDIT_COSTS,getUserAssessments,saveAssessment,saveCourseSubmission,spendCredits,trackEvent} from "@/lib/data";
const schema=z.object({scores:z.record(z.string(),z.number()),targetRole:z.string().optional(),targetCompany:z.string().optional(),xp:z.number().optional()});
export async function POST(req:NextRequest){const session=await getCurrentSession();if(!session)return NextResponse.json({error:"Sign in required"},{status:401});const body=await req.json().catch(()=>null) as any;const action=String(body?.action||"save").toLowerCase();
 if(action==="course_submit"){const p=z.object({courseId:z.string(),submissionText:z.string().min(20),projectUrl:z.string().url().optional(),deadlineAt:z.string().optional()}).safeParse(body);if(!p.success)return NextResponse.json({error:"Submit a meaningful project response"},{status:400});await saveCourseSubmission({course_id:p.data.courseId,user_id:session.sub,submission_text:p.data.submissionText,project_url:p.data.projectUrl||null,submitted_at:new Date().toISOString(),deadline_at:p.data.deadlineAt||null,status:"submitted"});await trackEvent("course_project_submitted",{userId:session.sub,meta:{courseId:p.data.courseId}});return NextResponse.json({ok:true});}
 if(action==="course_late_unlock"){const p=z.object({courseId:z.string()}).safeParse(body);if(!p.success)return NextResponse.json({error:"Course is required"},{status:400});try{await spendCredits(session.sub,CREDIT_COSTS.course_late_unlock,"course_late_unlock",p.data.courseId);await trackEvent("course_late_unlock",{userId:session.sub,meta:{courseId:p.data.courseId,cost:CREDIT_COSTS.course_late_unlock}});return NextResponse.json({ok:true,cost:CREDIT_COSTS.course_late_unlock});}catch(e){if(String(e).includes("INSUFFICIENT_CREDITS"))return NextResponse.json({error:"You need credits to continue this course.",code:"INSUFFICIENT_CREDITS"},{status:402});throw e;}}
 if(action==="course_certificate"){const p=z.object({courseId:z.string()}).safeParse(body);if(!p.success)return NextResponse.json({error:"Course is required"},{status:400});try{await spendCredits(session.sub,CREDIT_COSTS.course_certificate,"course_certificate",p.data.courseId);return NextResponse.json({ok:true,certificateId:`RSMFY-C-${Date.now().toString(36).toUpperCase()}`});}catch(e){if(String(e).includes("INSUFFICIENT_CREDITS"))return NextResponse.json({error:"You need credits for the course certificate.",code:"INSUFFICIENT_CREDITS"},{status:402});throw e;}}
 const parsed=schema.safeParse(body);if(!parsed.success)return NextResponse.json({error:"Invalid assessment payload"},{status:400});const {id,overall}=await saveAssessment(session.sub,parsed.data.scores,parsed.data.targetRole,parsed.data.targetCompany,parsed.data.xp??0);await trackEvent("assessment_saved",{userId:session.sub,meta:{overall}});return NextResponse.json({id,overall});}
export async function GET(){const session=await getCurrentSession();if(!session)return NextResponse.json({error:"Sign in required"},{status:401});return NextResponse.json({assessments:await getUserAssessments(session.sub)});}
