"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { api } from "@/lib/client";

export default function InvitePage(){
  const [data,setData]=useState<any>(null); const [error,setError]=useState(""); const [copied,setCopied]=useState(false);
  useEffect(()=>{api<any>("/api/track?action=user_invite_dashboard").then(setData).catch(e=>setError(e instanceof Error?e.message:"Sign in required"));},[]);
  const link=useMemo(()=>data?.profile?.invite_code?`${typeof window !== "undefined" ? window.location.origin : "https://resumeefy.com"}/?invite=${data.profile.invite_code}`:"",[data]);
  async function share(){ if(!link)return; const text="I use Resumeefy to prepare for jobs, resumes and interviews. Try it here:"; try{ if(navigator.share) await navigator.share({title:"Try Resumeefy",text,url:link}); else {await navigator.clipboard.writeText(`${text} ${link}`);setCopied(true);} }catch{} }
  async function copy(){if(!link)return; await navigator.clipboard?.writeText(link);setCopied(true);}
  if(!data && !error) return <main className="max-w-4xl mx-auto px-6 py-20">Loading…</main>;
  if(error) return <main className="max-w-xl mx-auto px-6 py-20"><div className="card p-8 text-center"><h1 className="font-display text-3xl font-semibold">Invite friends, earn a little extra</h1><p className="text-sm text-[var(--ink-soft)] mt-3">Log in to get your personal invite code.</p><Link href="/login?next=/invite" className="btn btn-primary mt-6">Log in</Link></div></main>;
  return <main className="max-w-5xl mx-auto px-6 py-16">
    <section className="rounded-[2rem] bg-[var(--ink)] text-white p-8 md:p-12 overflow-hidden relative"><div className="absolute -right-20 -top-20 w-64 h-64 rounded-full bg-[var(--blue)]/30 blur-3xl"/><span className="section-label light">FRIEND INVITES</span><h1 className="font-display text-4xl md:text-6xl font-semibold mt-3 max-w-3xl">Share Resumeefy. <em>Get a small thank you.</em></h1><p className="text-white/70 max-w-2xl mt-5">Your invite code is for friends and your own network. It is separate from the Resumeefy affiliate programme. When a friend joins through your link, you both receive a small credit reward.</p><div className="grid md:grid-cols-3 gap-3 mt-8"><div className="rounded-2xl bg-white/10 p-5"><b className="text-3xl">+10</b><p className="text-sm text-white/70 mt-1">credits for you when a referred friend joins</p></div><div className="rounded-2xl bg-white/10 p-5"><b className="text-3xl">+5</b><p className="text-sm text-white/70 mt-1">credits for your friend</p></div><div className="rounded-2xl bg-white/10 p-5"><b className="text-3xl">+1</b><p className="text-sm text-white/70 mt-1">tiny daily login reward, once per day</p></div></div></section>
    <section className="grid lg:grid-cols-[1.2fr_.8fr] gap-6 mt-6"><div className="card p-7"><span className="section-label">YOUR INVITE LINK</span><h2 className="font-display text-2xl font-semibold mt-2">Give a friend a head start</h2><div className="flex gap-2 mt-5"><input className="input" readOnly value={link}/><button className="btn btn-primary" onClick={copy}>{copied?"Copied":"Copy"}</button></div><button className="btn btn-primary mt-3 w-full justify-center" onClick={share}>Share with friends ↗</button><p className="text-xs text-[var(--ink-soft)] mt-3">Rewards are intentionally small. They help you keep using Resumeefy, but paid credit packs remain the main way to unlock higher value features.</p></div><div className="card p-7"><span className="section-label">YOUR PROGRESS</span><div className="grid grid-cols-2 gap-3 mt-5"><div className="rounded-2xl bg-[var(--paper)] p-4"><b className="text-3xl">{data.completedCount}</b><p className="text-xs text-[var(--ink-soft)] mt-1">friends joined</p></div><div className="rounded-2xl bg-[var(--paper)] p-4"><b className="text-3xl">{data.earned}</b><p className="text-xs text-[var(--ink-soft)] mt-1">referral credits earned</p></div></div><p className="text-sm text-[var(--ink-soft)] mt-5">Invite people who would genuinely benefit from Resumeefy. Repeated or self referrals do not qualify.</p></div></section>
  </main>;
}
